name: Main - Deploy slider server when notebooks change
on:
    push:
        branches:
            - main
        paths-ignore:
            - "website/**"
    workflow_dispatch:

jobs:
    deploy-slider-server:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout main source
              uses: actions/checkout@v2

            - name: Push to main-deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
                  BRANCH: main-deploy
                  FOLDER: .
