name: Deploy to Production
on:
  push:
    branches:
      - main-deploy
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Install DigitalOcean Controller
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker
      - name: Authenticate with DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 300 --verbose
      - name: Build and Push to DigitalOcean Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            registry.digitalocean.com/personal-apps-registry/pluto-slider-server:latest

  deploy-server:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Droplets already have docker, doctl + auth, and curl installed
      - name: Deploy Pluto slider server to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.DO_SERVER_HOST }}
          username: root
          key: ${{ secrets.DO_API_KEY }}
          port: 22
          script: |
            doctl registry login --expiry-seconds 180
            docker pull registry.digitalocean.com/personal-apps-registry/pluto-slider-server:latest

            docker stop pluto-slider-server || true
            docker rm pluto-slider-server || true

            echo "starting server instance..."
            docker run -d \
              --restart always \
              -p 0.0.0.0:80:1234 \
              --name pluto-slider-server \
              registry.digitalocean.com/personal-apps-registry/pluto-slider-server:latest