name: Main - Export Pluto notebooks & Deploy NextJS blog
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout main source
              uses: actions/checkout@v2

            - name: Set up notebook state cache
              uses: actions/cache@v2
              with:
                path: pluto_state_cache
                key: ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}-${{ hashFiles('**/*.jl') }}
                restore-keys: |
                    ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}

            - name: Install Julia
              uses: julia-actions/setup-julia@v1
              with:
                  version: 1.6.0
            - name: Run Pluto notebooks
              run: julia --project=pluto-deployment-environment tools/run_pluto_notebooks.jl
            - name: NextJS
              run: julia tools/setup_nextjs.jl
            - name: Build and Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: main-nextjs-output
                  FOLDER: website/