name: Main - Export Pluto notebooks & Deploy
on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout main source
              uses: actions/checkout@v2

            - name: Set up notebook state cache
              uses: actions/cache@v2
              with:
                path: pluto_state_cache
                key: ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}-${{ hashFiles('**/*.jl') }}
                restore-keys: |
                    ${{ runner.os }}-pluto_state_cache-v2-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}

            - name: Install Julia
              uses: julia-actions/setup-julia@v1
              with:
                  version: 1.6.0
            - name: Run Pluto notebooks
              run: julia --project=pluto-deployment-environment -e '
                  import Pkg;
                  Pkg.instantiate();

                  using PlutoSliderServer;
                  github_action("."; Export_cache_dir="pluto_state_cache");'
            - name: Franklin
              run: julia -e '
                  using Pkg;
                  Pkg.add([
                  Pkg.PackageSpec(name="NodeJS", version="1.1.1"),
                  Pkg.PackageSpec(name="JSON", version="0.21.1"),
                  Pkg.PackageSpec(name="Franklin", version="0.10.28"),
                  ]);
                  using NodeJS;

                  "== Run Franklin ==";
                  cd("website");

                  run(`$(npm_cmd()) install highlight.js`);
                  using Franklin;
                  optimize(;minify=false);

                  "== Place rendered notebooks in the website folder ==";
                  cp("../notebooks", "__site/notebooks");

                  "== Extra website config files ==";
                  write("__site/CNAME", "interactive.zohaib.me");'
            - name: Build and Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: main-franklin-output
                  FOLDER: website/__site
